package com.work.challengeyapeapp.core

const val AMERICAN_LATITUDE = 37.0902
const val AMERICAN_LONGITUDE = -95.7129
const val BRITISH_LATITUDE = 51.5074
const val BRITISH_LONGITUDE = 0.1278
const val CANADIAN_LATITUDE = 56.1304
const val CANADIAN_LONGITUDE = -106.3468
const val CHINESE_LATITUDE = 35.8617
const val CHINESE_LONGITUDE = 104.1954
const val CROATIAN_LATITUDE = 45.1
const val CROATIAN_LONGITUDE = 15.2
const val DUTCH_LATITUDE = 52.1326
const val DUTCH_LONGITUDE = 5.2913
const val EGYPTIAN_LATITUDE = 26.8206
const val EGYPTIAN_LONGITUDE = 30.8025
const val FRENCH_LATITUDE = 46.2276
const val FRENCH_LONGITUDE = 2.2137
const val GREEK_LATITUDE = 39.0742
const val GREEK_LONGITUDE = 21.8243
const val INDIAN_LATITUDE = 20.5937
const val INDIAN_LONGITUDE = 78.9629
const val IRISH_LATITUDE = 53.1424
const val IRISH_LONGITUDE = -7.6921
const val ITALIAN_LATITUDE = 41.8719
const val ITALIAN_LONGITUDE = 12.5674
const val JAPANESE_LATITUDE = 36.2048
const val JAPANESE_LONGITUDE = 138.2529
const val MEXICAN_LATITUDE = 23.6345
const val MEXICAN_LONGITUDE = -102.5528
const val RUSSIAN_LATITUDE = 61.5240
const val RUSSIAN_LONGITUDE = 105.3188
const val SPANISH_LATITUDE = 40.4637
const val SPANISH_LONGITUDE = -3.7492
const val TURKISH_LATITUDE = 38.9637
const val TURKISH_LONGITUDE = 35.2433
const val VIETNAMESE_LATITUDE = 14.0583
const val VIETNAMESE_LONGITUDE = 108.2772
const val AUSTRALIAN_LATITUDE = -25.2744
const val AUSTRALIAN_LONGITUDE = 133.7751
const val BRAZILIAN_LATITUDE = -14.2350
const val BRAZILIAN_LONGITUDE = -51.9253
const val GERMAN_LATITUDE = 51.1657
const val GERMAN_LONGITUDE = 10.4515
const val KOREAN_LATITUDE = 35.9078
const val KOREAN_LONGITUDE = 127.7669
const val SWEDISH_LATITUDE = 60.1282
const val SWEDISH_LONGITUDE = 18.6435
const val SWISS_LATITUDE = 46.8182
const val SWISS_LONGITUDE = 8.2275
const val THAI_LATITUDE = 15.8700
const val THAI_LONGITUDE = 100.9925
const val BELGIAN_LATITUDE = 50.5039
const val BELGIAN_LONGITUDE = 4.4699
const val AUSTRIAN_LATITUDE = 47.5162
const val AUSTRIAN_LONGITUDE = 14.5501
const val DANISH_LATITUDE = 56.2639
const val DANISH_LONGITUDE = 9.5018
const val PORTUGUESE_LATITUDE = 39.3999
const val PORTUGUESE_LONGITUDE = -8.2245
const val POLISH_LATITUDE = 51.9194
const val POLISH_LONGITUDE = 19.1451
const val HUNGARIAN_LATITUDE = 47.1625
const val HUNGARIAN_LONGITUDE = 19.5033
const val MOROCCAN_LATITUDE = 31.7917
const val MOROCCAN_LONGITUDE = -7.0926
const val TUNISIAN_LATITUDE = 33.8869
const val TUNISIAN_LONGITUDE = 9.5375
const val FILIPINO_LATITUDE = 12.8797
const val FILIPINO_LONGITUDE = 121.7740
const val KENYAN_LATITUDE = -1.2921
const val KENYAN_LONGITUDE = 36.8219
const val MALAYSIAN_LATITUDE = 4.2105
const val MALAYSIAN_LONGITUDE = 101.9758
const val JAMAICAN_LATITUDE = 18.1096
const val JAMAICAN_LONGITUDE = -77.2975
const val UNKNOWN_LATITUDE = 37.0000
const val UNKNOWN_LONGITUDE = -95.0000

enum class Gentiles (val coordinates: Pair<Double, Double>){
    American (AMERICAN_LATITUDE to AMERICAN_LONGITUDE),
    British (BRITISH_LATITUDE to BRITISH_LONGITUDE),
    Canadian (CANADIAN_LATITUDE to CANADIAN_LONGITUDE),
    Chinese (CHINESE_LATITUDE to CHINESE_LONGITUDE),
    Croatian (CROATIAN_LATITUDE to CROATIAN_LONGITUDE),
    Dutch (DUTCH_LATITUDE to DUTCH_LONGITUDE),
    Egyptian (EGYPTIAN_LATITUDE to EGYPTIAN_LONGITUDE),
    French (FRENCH_LATITUDE to FRENCH_LONGITUDE),
    Greek (GREEK_LATITUDE to GREEK_LONGITUDE),
    Indian (INDIAN_LATITUDE to INDIAN_LONGITUDE),
    Irish (IRISH_LATITUDE to IRISH_LONGITUDE),
    Italian (ITALIAN_LATITUDE to ITALIAN_LONGITUDE),
    Japanese (JAPANESE_LATITUDE to JAPANESE_LONGITUDE),
    Mexican (MEXICAN_LATITUDE to MEXICAN_LONGITUDE),
    Russian (RUSSIAN_LATITUDE to RUSSIAN_LONGITUDE),
    Spanish (SPANISH_LATITUDE to SPANISH_LONGITUDE),
    Turkish (TURKISH_LATITUDE to TURKISH_LONGITUDE),
    Vietnamese (VIETNAMESE_LATITUDE to VIETNAMESE_LONGITUDE),
    Australian (AUSTRALIAN_LATITUDE to AUSTRALIAN_LONGITUDE),
    Brazilian (BRAZILIAN_LATITUDE to BRAZILIAN_LONGITUDE),
    German (GERMAN_LATITUDE to GERMAN_LONGITUDE),
    Korean (KOREAN_LATITUDE to KOREAN_LONGITUDE),
    Swedish (SWEDISH_LATITUDE to SWEDISH_LONGITUDE),
    Swiss (SWISS_LATITUDE to SWISS_LONGITUDE),
    Thai (THAI_LATITUDE to THAI_LONGITUDE),
    Belgian (BELGIAN_LATITUDE to BELGIAN_LONGITUDE),
    Austrian (AUSTRIAN_LATITUDE to AUSTRIAN_LONGITUDE),
    Danish (DANISH_LATITUDE to DANISH_LONGITUDE),
    Portuguese (PORTUGUESE_LATITUDE to PORTUGUESE_LONGITUDE),
    Polish (POLISH_LATITUDE to POLISH_LONGITUDE),
    Hungarian (HUNGARIAN_LATITUDE to HUNGARIAN_LONGITUDE),
    Moroccan (MOROCCAN_LATITUDE to MOROCCAN_LONGITUDE),
    Tunisian (TUNISIAN_LATITUDE to TUNISIAN_LONGITUDE),
    Filipino (FILIPINO_LATITUDE to FILIPINO_LONGITUDE),
    Kenyan (KENYAN_LATITUDE to KENYAN_LONGITUDE),
    Malaysian (MALAYSIAN_LATITUDE to MALAYSIAN_LONGITUDE),
    Jamaican (JAMAICAN_LATITUDE to JAMAICAN_LONGITUDE),
    Unknown (UNKNOWN_LATITUDE to UNKNOWN_LONGITUDE)
}
